name = "fio-de-bengal"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fio-db"
database_id = "d6491928-8437-4b16-a6f5-c7ee543a4ccf"
